name: Generate Contribution Activity Graph

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/snake.yml'

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: yashcx84
          THEME: tokyo-night
          CUSTOM_TITLE: Yash Jangid's Contribution Graph
          AREA: true

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: profile-cheat-sheet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}